### ISSUE TITLE
Build Failure: panic: http: multiple registrations for /debug/requests

### ISSUE THREAD

**Issue by bradleyfalzon** [bradleyfalzon/gopherci#101]
Recently, GopherCI has been failing to compile from master (and recent build failure in #100).

```
panic: http: multiple registrations for /debug/requests

goroutine 1 [running]:
net/http.(*ServeMux).Handle(0xb42e60, 0x8e0038, 0xf, 0xaf9860, 0x8f4e18)
        /usr/local/go/src/net/http/server.go:2254 +0x610
net/http.(*ServeMux).HandleFunc(0xb42e60, 0x8e0038, 0xf, 0x8f4e18)
        /usr/local/go/src/net/http/server.go:2286 +0x55
net/http.HandleFunc(0x8e0038, 0xf, 0x8f4e18)
        /usr/local/go/src/net/http/server.go:2298 +0x4b
golang.org/x/net/trace.init.1()
        /home/bradleyf/go/src/golang.org/x/net/trace/trace.go:115 +0x42
golang.org/x/net/trace.init()
        /home/bradleyf/go/src/golang.org/x/net/trace/trace_go17.go:22 +0x1cd
google.golang.org/grpc.init()
        /home/bradleyf/go/src/google.golang.org/grpc/trace.go:105 +0x87
main.init()
        /home/bradleyf/go/src/github.com/bradleyfalzon/test/debug-requests/main.go:15 +0x4e
```

After further investigation, it appears to be because `golang.org/x/net/trace` is registering for the `/debug/requests` in its init function on the `DefaultServeMux` in `net/http` - not once but multiple times - no other package is registering that pattern. Note, we're not using this mux, so this registration behaviour is futile.

This normally isn't a problem, multiple packages can import `golang.org/x/net/trace` and the same init function is only ever invoked once; no matter how many times it's imported. It's only a problem if different packages try to register this pattern on the same mux (again, in my case, they are not).

For example, two packages importing `golang.org/x/net/trace` successfully (how things were for me):

```bash
docker run -it --rm  golang:1.8 bash
root@d9313a91efee:/go# mkdir -p src/{alice/repo/lib,bob/repo/prog}
root@d9313a91efee:/go# cd src/alice/repo/lib
root@d9313a91efee:/go/src/alice/repo/lib# cat > lib.go <<EOF
> package lib
>
> import _ "golang.org/x/net/trace"
> EOF
root@d9313a91efee:/go/src/alice/repo/lib# cd $GOPATH/src/bob/repo/prog/
root@d9313a91efee:/go/src/bob/repo/prog# cat > main.go <<EOF
> package main
>
> import (
>     "fmt"
>
>     _ "alice/repo/lib"
>     _ "golang.org/x/net/trace"
> )
>
> func main() {
>     fmt.Println("Hello, World!")
> }
> EOF
root@d9313a91efee:/go/src/bob/repo/prog# go get
root@d9313a91efee:/go/src/bob/repo/prog# go get github.com/golang/dep/cmd/dep # we'll use this shortly
root@d9313a91efee:/go/src/bob/repo/prog# go run main.go
Hello, World!
```

Above we've created our main package which imports `golang.org/x/net/trace` as well as another package which imports `golang.org/x/net/trace`. _This example imports `trace` but doesn't use it, in the real world both packages would use some of its exported functions._

We can see that although two packages import `golang.org/x/net/trace`, the init function is only called once (there's no panic) and the program executes successfully.

However, once the library we're using vendors `golang.org/x/net/trace`, we have different behaviour.

```
root@d9313a91efee:/go/src/bob/repo/prog# ( cd $GOPATH/src/alice/repo/lib/ && dep init && find . -maxdepth 4 )
  Using master as constraint for direct dep golang.org/x/net
  Locking in master (f5079bd) for direct dep golang.org/x/net
.
./Gopkg.lock
./lib.go
./Gopkg.toml
./vendor
./vendor/golang.org
./vendor/golang.org/x
./vendor/golang.org/x/net
root@d9313a91efee:/go/src/bob/repo/prog# go run main.go
panic: http: multiple registrations for /debug/requests

goroutine 1 [running]:
net/http.(*ServeMux).Handle(0x8ee480, 0x75969f, 0xf, 0x8bbf80, 0x76a1d8)
        /usr/local/go/src/net/http/server.go:2254 +0x610
net/http.(*ServeMux).HandleFunc(0x8ee480, 0x75969f, 0xf, 0x76a1d8)
        /usr/local/go/src/net/http/server.go:2286 +0x55
net/http.HandleFunc(0x75969f, 0xf, 0x76a1d8)
        /usr/local/go/src/net/http/server.go:2298 +0x4b
alice/repo/lib/vendor/golang.org/x/net/trace.init.1()
        /go/src/alice/repo/lib/vendor/golang.org/x/net/trace/trace.go:115 +0x42
alice/repo/lib/vendor/golang.org/x/net/trace.init()
        /go/src/alice/repo/lib/vendor/golang.org/x/net/trace/trace_go17.go:22 +0x1cd
alice/repo/lib.init()
        /go/src/alice/repo/lib/lib.go:4 +0x44
main.init()
        /go/src/bob/repo/prog/main.go:13 +0x4e
exit status 2
```

`trace`'s init function is now called multiple times, resulting in the same http handler being registered multiple times, and causing the panic.

The only change here was our dependency vendored their dependencies, now our code panics. Here, someone else's vendoring (and committing the vendor directory) was a breaking change.

We can resolve this by vendoring the dependencies ourselves and flattening the vendor tree. This is something `github.com/golang/dep` should do itself, but didn't for some reason, so I've done it here manually:

```
root@d9313a91efee:/go/src/bob/repo/prog# dep init
  Using master as constraint for direct dep golang.org/x/net
  Locking in master (f5079bd) for direct dep golang.org/x/net
root@d9313a91efee:/go/src/bob/repo/prog# cp -R $GOPATH/src/alice vendor/
root@d9313a91efee:/go/src/bob/repo/prog# rm -rf vendor/alice/repo/lib/vendor
root@d9313a91efee:/go/src/bob/repo/prog# go run main.go
Hello, World!
```

**Comment by bradleyfalzon** [comment]
In our case it's happening because we import Google's PubSub package, which imports grpc which imports trace, and moby imports grpc which imports trace. Recently moby has began vendoring their dependencies causing this panic.

**Comment by bradleyfalzon** [comment]
Our soltution then appears to be (and what I should've done previously), is to vendor (and flatten) GopherCI dependencies.
