### ISSUE TITLE
Max build time

### ISSUE THREAD

**Issue by bradleyfalzon** [bradleyfalzon/gopherci#53]
GopherCI should set a maximum build time, appears the some bugs in Docker cause an execution to never return:

```
Jan 28 19:40:17 www1.c.gopherci-prod.internal dockerd[6742]: panic: close of nil channel
Jan 28 19:40:17 www1.c.gopherci-prod.internal dockerd[6742]: goroutine 618 [running]:
Jan 28 19:40:17 www1.c.gopherci-prod.internal dockerd[6742]: panic(0x8078a0, 0xc4203fcac0)
Jan 28 19:40:17 www1.c.gopherci-prod.internal dockerd[6742]: /usr/local/go/src/runtime/panic.go:500 +0x1a1
Jan 28 19:40:17 www1.c.gopherci-prod.internal dockerd[6742]: github.com/docker/containerd/supervisor.(*Supervisor).execExit.func1(0xc420450be0, 0xc4200f9a00, 0x0)
Jan 28 19:40:17 www1.c.gopherci-prod.internal dockerd[6742]: /go/src/github.com/docker/containerd/supervisor/exit.go:90 +0x10c
Jan 28 19:40:17 www1.c.gopherci-prod.internal dockerd[6742]: created by github.com/docker/containerd/supervisor.(*Supervisor).execExit
Jan 28 19:40:17 www1.c.gopherci-prod.internal dockerd[6742]: /go/src/github.com/docker/containerd/supervisor/exit.go:91 +0xee
Jan 28 19:40:18 www1.c.gopherci-prod.internal dockerd[6742]: time="2017-01-28T19:40:18.860760730+10:30" level=error msg="libcontainerd: failed to receive event from containerd: rpc error: code = 13 desc = transport is closing"
Jan 28 19:40:18 www1.c.gopherci-prod.internal dockerd[6742]: time="2017-01-28T19:40:18.955680383+10:30" level=info msg="libcontainerd: new containerd process, pid: 30204"
Jan 28 19:40:19 www1.c.gopherci-prod.internal dockerd[6742]: time="2017-01-28T19:40:19.501709668+10:30" level=info msg="libcontainerd: new containerd process, pid: 30211"
```

**Comment by bradleyfalzon** [comment]
acc4a15b1052fc4010c5e44e29e606a4f8a2260f now has a context with a large timeout that can be used for this purpose.
